version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    assignees: ["0xfell"]
    reviewers: ["0xfell"]
    labels: ["dependencies", "cargo"]
    groups:
      minor-and-patch:
        applies-to: security-updates
        patterns: ["*"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "America/Los_Angeles"
    open-pull-requests-limit: 10
    assignees: ["0xfell"]
    reviewers: ["0xfell"]
    labels: ["dependencies", "actions"]
