[graph]
all-features = true

[advisories]
# cargo-deny >=0.16 removes 'vulnerability' and 'notice'; advisories are denied by default.
unmaintained = "workspace"
yanked = "warn"
ignore = []

[bans]
multiple-versions = "warn"
deny = []
# Allow common duplicates until we choose to unify
wildcards = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "OpenSSL",
  "MPL-2.0",
  "MIT-0",
  "BSL-1.0",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
