[graph]
all-features = true

[advisories]
# cargo-deny >=0.16 removes 'vulnerability' and 'notice'; advisories are denied by default.
unmaintained = "workspace"
yanked = "warn"
ignore = [
  # GTK3/gtk-rs ecosystem advisories only pulled in by optional `tray` feature
  "RUSTSEC-2024-0412", # gdk unmaintained
  "RUSTSEC-2024-0413", # atk unmaintained
  "RUSTSEC-2024-0415", # gtk unmaintained
  "RUSTSEC-2024-0416", # atk-sys unmaintained
  "RUSTSEC-2024-0418", # gdk-sys unmaintained
  "RUSTSEC-2024-0419", # gtk3-macros unmaintained
  "RUSTSEC-2024-0420", # gtk-sys unmaintained
  # glib unsound VariantStrIter — affects gtk* chain above; tray-only
  "RUSTSEC-2024-0429",
  # proc-macro-error unmaintained — transitively via gtk3-macros
  "RUSTSEC-2024-0370",
]

[bans]
multiple-versions = "warn"
deny = []
# Allow common duplicates until we choose to unify
wildcards = "allow"

[licenses]
allow = [
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "OpenSSL",
  "MPL-2.0",
  "MIT-0",
  "BSL-1.0",
  "Unicode-3.0",
  "CDLA-Permissive-2.0",
]
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
