[graph]
all-features = true

[advisories]
# deny any vulnerable advisories; allow yanked (often false positives)
vulnerability = "deny"
yanked = "warn"
unmaintained = "warn"
notice = "warn"
ignore = []

[bans]
multiple-versions = "warn"
denied = []
# Allow common duplicates until we choose to unify
wildcards = "allow"

[licenses]
unlicensed = "deny"
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "OpenSSL",
  "MPL-2.0",
  "MIT-0",
]
# Some crates mark license as OR variants; treat them as allowed
copyleft = "warn"
confidence-threshold = 0.8

[sources]
unknown-registry = "warn"
unknown-git = "warn"
