[advisories]
# Ignore INFO-level advisory about `paste` being unmaintained (RUSTSEC-2024-0436).
# Rationale: Transitive via `ratatui` and no patched replacement yet; upstream
# suggests `pastey` but it cannot be transparently substituted for transitive deps.
# We revisit quarterly or when ratatui migrates.
ignore = ["RUSTSEC-2024-0436"]

# Treat unmaintained as warnings; we still fail on warnings in CI, but the
# above specific advisory is ignored to avoid blocking.
informational_warnings = ["unmaintained"]

[database]
url = "https://github.com/RustSec/advisory-db.git"
fetch = true
stale = false

[output]
format = "terminal"
quiet = false
show_tree = true
