name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: Tests
        run: cargo test --workspace --all-features --no-fail-fast
      - name: Build release (CLI)
        run: cargo build --release -p ditox-cli
      - name: Package artifact
        run: |
          mkdir -p dist
          cp target/release/ditox-cli dist/
          tar -czf dist/ditox-cli-linux-x86_64.tar.gz -C dist ditox-cli
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ditox-cli-linux-x86_64
          path: dist/ditox-cli-linux-x86_64.tar.gz

