name: Debug Secrets

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Report actor and ref
        run: |
          echo "actor=${{ github.actor }}"
          echo "ref=${{ github.ref }}"
      - name: Secret present
        if: ${{ secrets.TEST_SECRET != '' }}
        run: echo "TEST_SECRET is present"
      - name: Secret missing
        if: ${{ secrets.TEST_SECRET == '' }}
        run: echo "TEST_SECRET is missing"
      - name: Token present
        if: ${{ secrets.CARGO_REGISTRY_TOKEN != '' }}
        run: echo "CARGO_REGISTRY_TOKEN is present"
      - name: Token missing
        if: ${{ secrets.CARGO_REGISTRY_TOKEN == '' }}
        run: echo "CARGO_REGISTRY_TOKEN is missing"

