name: Nix CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    nix:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Nix
              uses: cachix/install-nix-action@v27
              with:
                  extra_nix_config: |
                      experimental-features = nix-command flakes
            - name: Build flake
              run: nix build -L .#ditox
            - name: Run flake checks
              run: nix flake check -L
            - name: Archive binary
              run: |
                  mkdir -p dist
                  cp result/bin/ditox-cli dist/
                  tar -czf dist/ditox-cli-nix-linux-x86_64.tar.gz -C dist ditox-cli
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ditox-cli-nix-linux-x86_64
                  path: dist/ditox-cli-nix-linux-x86_64.tar.gz
